// Code generated by go-mock; DO NOT EDIT.

package main

import (
    "context"
    _mock "github.com/xhd2015/go-mock/mock"
)

const _SKIP_MOCK = true
const FULL_PKG_NAME = "github.com/xhd2015/go-mock/example/demo"

func Setup(ctx context.Context,setup func(m *M)) context.Context {
    m:=M{}
    setup(&m)
    return _mock.WithMockSetup(ctx,FULL_PKG_NAME,m)
}


type M struct {
    M_main func()
}

/* prodives quick link */
var _ = func() { type Pair [2]interface{};_ = map[string]interface{}{
}}
